name: test
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/api/go
    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: test
        run: go test

